GET http://localhost:3000/highscores

###

POST http://localhost:3000/highscores
Content-Type: application/json

{
    "name": "Stoiko",
    "time": 74
}

###

GET http://localhost:3000/highscores/top3

